name: ${PROJECT}

networks:
  default:
    name: ${PROJECT}
    driver: bridge
services:
  wp:
    userns_mode: keep-id:uid=33,gid=33
    build:
      context: .
    container_name: ${PROJECT}-wp
    volumes:
      - ./wp-content:/var/www/html/wp-content:Z
      - ./xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:Z
      - ./log:/var/log:Z
    ports:
      - 8080:80